project:
  type: website

website:
  title: "Jacobs Research Network"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - members.qmd
      - products.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

