---
title: "About"
---

## A balanced view
In the public domain, people who belong to systematically disadvantaged groups are often cast in a negative light. The discourse uses the language of deficit (e.g., ‘impaired’ cognition) and emphasizes (what are thought to be) flawed decisions (e.g., an ‘inability’ to delay gratification). However:
 
  1. *Disparities between people from systematically advantaged and disadvantaged groups may often be the result of factors other than impaired ability.* For instance, making learning and testing materials more relevant can help or hinder performance.
 
  2. *People also develop unique knowledge, perspectives, values, strengths, and strategies as a result of their lived experiences associated with their identity and background.* For instance, they might be more attuned to other people’s thoughts and feelings.

  3. *People make decisions that can be understood as a response to their environment.* For instance, they might invest less in future rewards if these are unlikely to materialize.

## Products
 Our products offer a broad, humanistic view on people who belong to systematically disadvantaged groups. We create a wide variety of products, such as infographics, fact sheets, animations, and scientific articles.